### PR TITLE
added innodb configuration to support utf-8

### PR DESCRIPTION
**Pull request by jdispirito**

### CODE REVIEW

**Comment by febbraro** [comment]
Do we also need to set the default encoding and collation to `utf8mb4`?

**Comment by grayside** [comment]
This image is not specifically for Drupal, so rather than have a Drupal-specific settings file baked into it, it seems to me that we should:

* Configure this image to support UTF-8 by default without talking about Drupal except as a documentation reference on how we set it up. (e.g., take drupal out of the filename)
* Have a UTF-8 support mode toggled by environment variable, similar to PHP_XDEBUG for the apache-php images.

If this approach to UTF-8 support is idiosyncratic for Drupal, we might also consider adding a mariadb-drupal Docker image to extend from this to hold app-specific optimizations.

**Comment by jdispirito** [comment]
https://www.drupal.org/node/2754539   This link contains the original configuration information

**Comment by febbraro** [comment]
Not sure what do to about this, but innodb_large_prefix is deprecated in 10.2.

https://mariadb.com/kb/en/mariadb/xtradbinnodb-server-system-variables/#innodb_large_prefix

What is taking it's place?

**Comment by febbraro** [comment]
It also appears to have been set to ON by default in 10.2.2 and greater, wtf?

**Comment by tekante** [comment]
innodb_file_per_table has been the default since MariaDB 5.5 and is already set via the generated server.cnf file so it seems redundant here.

innodb_large_prefix defaults to on and innodb_file_format defaults to barracuda at 10.2.2 so this seems an interim configuration needed until 10.2 drops as stable and we upgrade to that. They are both marked as deprecated because you aren't going to have the option to turn them to their old values in the future. See https://dev.mysql.com/worklog/task/?id=7703

Can we add a comment to the effect that these are interim settings until the defaults of 10.2.2 to ensure full 4 byte utf8 support and potentially point or copy the explanatory note for these settings midway down https://dev.mysql.com/doc/refman/5.7/en/charset-unicode-conversion.html (I couldn't find a corollary mariadb page with as nice a snippet explanation unfortunately)

Otherwise this looks good to me.

**Comment by febbraro** [comment]
Which other version do we want this on? 5.5? 10.0? 10.2?  (I will merge this but wanted our path forward as this repo needs to be flattened)

**Comment by tekante** [comment]
I think we only need it in 5.5 as in 10.2.2 and above these are all the defaults as near as I can tell.

**Pull request merged**
